### PR TITLE
Upgrade dependencies

### PR DESCRIPTION
**Pull request by romainnorberg**
- force php >= 7.2
- use `endroid/qr-code` last release
- use `phpunit/phpunit` last release _(`assertInternalType` is deprecated)_

### CODE REVIEW

**Comment by smhg** [comment]
Great PR! Thanks!
Released as: 3.0.0

**Comment by romainnorberg** [comment]
thanks to you @smhg 😃

**Comment by smhg** [comment]
@romainnorberg do you remember why you chose `php` 7.2 and `endroid/qr-code` 3.6 in this PR?

I'm stuck with php 7.1 on a project and downgrading endroid/qr-code to 3.5 is the only thing necessary to support that version. Was there anything specific in 3.6 (or later)?

Maybe it's not the best idea, but as an intermediate release it might be ok.

**Comment by romainnorberg** [comment]
Hello @smhg 

Because projects in which we use sepa-qr-php requires phpunit >=8 and phpunit 8 require >=7.2 (and `endroid/qr-code` also in 3.6 (https://github.com/endroid/qr-code/compare/3.5.9...3.6.0))

No solution to migrate your project to 7.2? 7.1 has not been supported for several weeks (https://www.php.net/supported-versions.php)

**Comment by smhg** [comment]
PHP might be moving a bit fast for old projects these days ;) No, you're absolutely right of course.

I was just trying to figure out how necessary 7.2 was.
For phpunit, it could be solved by using a spec like `"^7||^8"`, right? I'm not that fluent in PHP these days.

**Comment by romainnorberg** [comment]
I thing you can use composer alias to solve this problem: https://blog.programster.org/composer-aliases 

If not, an release like 2.x could maybe solve your problem

**Comment by smhg** [comment]
@romainnorberg I managed to configure it like this:
```json
    "require": {
        "php": "^7.1",
        "endroid/qr-code": "^3"
    },
    "require-dev": {
        "phpunit/phpunit": "^7||^8"
    }
```
This way you get the right `endroid/qr-code` and `phpunit` versions on both 7.1 and 7.2 (and up). So the new release ([3.1.0](https://github.com/smhg/sepa-qr-php/releases/tag/v3.1.0)) won't change anything for you (on 7.2 or up).

Thank you for your feedback!

_Disclaimer_: yes (now) supporting PHP 7.1 is absolutely silly. However, it was this easy and can of course be removed in again in a future version.

_Sidenote (and justification)_: coming from JS, I don't really understand how PHP and some libraries (looking at you, `endroid/qr-code`) handle semver. PHP 7.2 seems to introduce backwards incompatible changes? Shouldn't libraries just support v5 and/or v7 (the whole major version)? It's a bit awkward.

**Pull request merged**
